import { parse } from '.'

it('should parse media query', async () => {
  expect(parse('only screen and (color)')).toBe('')
  expect(parse('not print and (min-width: 10px)')).toBe('')
  expect(parse('not print, screen, (max-width: 1000px)')).toBe('')
  expect(parse('url(fun()) screen and (color), projection and (color)')).toBe(
    null
  )
  expect(parse('all, all, all')).toBe('')
  expect(parse('all,, all')).toBe(null)
  expect(parse(',all, all')).toBe(null)
  expect(parse('(all, all), all')).toBe(null)
  expect(parse('((min-width: -100px)')).toBe(null)

  expect(parse('(max-width:1199.98px)')).toBe('')
  expect(parse('(max-width:1399.98px)')).toBe('')
  expect(parse('(max-width:575.98px)')).toBe('')
  expect(parse('(max-width:767.98px)')).toBe('')
  expect(parse('(max-width:991.98px)')).toBe('')
  expect(parse('(min-width:1200px)')).toBe('')
  expect(parse('(min-width:1400px)')).toBe('')
  expect(parse('(min-width:576px)')).toBe('')
  expect(parse('(min-width:768px)')).toBe('')
  expect(parse('(min-width:992px)')).toBe('')
  expect(parse('(prefers-reduced-motion:no-preference)')).toBe('')
  expect(parse('(any-hover:hover)')).toBe('')
  expect(parse('(any-hover:none)')).toBe('')
  expect(parse('(any-hover:anything)')).toBe('')
  expect(parse('(grid:0)')).toBe('')
  expect(parse('(aspect-ratio:16/9)')).toBe('')
  expect(parse('(prefers-reduced-motion:reduce)')).toBe('')
  expect(parse('print')).toBe('')
  expect(parse('(height > 600px)')).toBe('')
  expect(parse('(600px < height)')).toBe('')
  expect(parse('(600px > width)')).toBe('')
  expect(parse('(width < 600px)')).toBe('')
  expect(parse('(100px <= width <= 200px)')).toBe('')
  expect(parse('screen and (100px <= width <= 200px)')).toBe('')
  expect(parse('(100px <= width) and (width <= 200px)')).toBe('')
})
